// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json([
  
    {
      id:0,
      nombre:"Paco",
      edad:4,
      sexo: "Macho",
      color:"Blanco con café",
      tamaño: "Grande",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      Castrado:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/apolo1.jpg"  
    },
    {
      id:1,
      nombre:"Mila",
      edad:9,
      sexo: "Hembra",
      color:"Blanco con negro",
      tamaño: " Mediano",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/lucy1.jpg"
    },
    {
      id:2,
      nombre:"Pica",
      edad:4,
      sexo: "Hembra",
      color:"Blanco con cafe",
      tamaño: " Mediano",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/benji21.jpg"
    },
    {
      id:3,
      nombre:"Chanda",
      edad:1,
      sexo: "Macho",
      color:"cafe",
      tamaño: "Grande",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      Castrado:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/jerry1.jpg"
    },
    {
      id:4,
      nombre:"Negra",
      edad:1,
      sexo: "Hembra",
      color:"Negro",
      tamaño: "Mediano",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/ramona1.jpg"
    },
    {
      id:5,
      nombre:"Pirulito",
      edad:5,
      sexo: "Macho",
      color:"Blanco con gris",
      tamaño: "Grande",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      castrado:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/angel1.jpg"
    },
    {
      id:6,
      nombre:"Paola",
      edad:5,
      sexo: "Hembra",
      color:"Negro",
      tamaño: "Grande",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/salma.jpg"
    },
    {
      id:7,
      nombre:"Mona",
      edad:2,
      sexo: "Hembra",
      color:"Negro y café",
      tamaño: "Grande",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/pola1.jpg"
    },
    {
      id:8,
      nombre:"Milagrito",
      edad:7,
      sexo: "Hembra",
      color:"Tricolor",
      tamaño: "Pequeña",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/princesa1.jpg"
    },
    {
      id:9,
      nombre:"Copito",
      edad:9,
      sexo: "Hembra",
      color:"Blanco",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/samy1.jpg"
    },
    {
      id:10,
      nombre:"hachi",
      edad:1,
      sexo: "Hembra",
      color:"Negro",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/milu21.jpg"
    },
    {
      id:11,
      nombre:"Ojitos",
      edad:2,
      sexo: "Hembra",
      color:"Café",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/06/tadeo1.jpg"
    },
    {
      id:12,
      nombre:"Miel",
      edad:2,
      sexo: "Hembra",
      color:"Café",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/naoki1.jpg"
    },
    {
      id:13,
      nombre:"Papolo",
      edad:2,
      sexo: "Macho",
      color:"Café con Negro",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      castrado:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/11/toto1.jpg"
    },
    {
      id:14,
      nombre:"Atenea",
      edad:5,
      sexo: "Hembra",
      color:"Café ",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2021/04/atena1.jpg"
    },
    {
      id:15,
      nombre:"Cacao",
      edad:5,
      sexo: "Hembra",
      color:"Café ",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2021/09/miranda21.jpg"
    },
    {
      id:16,
      nombre:"Monito",
      edad:5,
      sexo: " Macho",
      color:"Café ",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      castrado:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2022/01/pocker1.jpg"
    },
    {
      id:17,
      nombre:"Lula",
      edad:10,
      sexo: "Hembra",
      color:"Negro y Blanco",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2021/05/raiza1.jpg"
    },
    {
      id:18,
      nombre:"Zafira",
      edad:6,
      sexo: "Hembra",
      color:"Negro con café",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      esterilizada:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2021/05/rita1.jpg"
    },
    {
      id:19,
      nombre:"Rojo",
      edad:6,
      sexo: "Macho",
      color:"Gris con café",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      castrado:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2021/06/toby1.jpg"
    },
    {
      id:20,
      nombre:"totoro",
      edad:6,
      sexo: "Macho",
      color:"Café",
      tamaño: "Mediana",
      estadodesalud:"Bueno",
      vacunado: "Sí",
      castrado:"Sí",
      foto:"https://www.fundaciontepa.org/wp-content/uploads/2021/06/tono1.jpg"
    },
  ]
 )
}
