import Head from 'next/head'
import style from '../styles/Layaut.module.css'
import { createTheme, ThemeProvider } from '@mui/material/styles';
import {  amber, brown,blue } from '@mui/material/colors';
export default function Layout({children,title}) {
  const theme = createTheme({
    palette: {
      primary: {
        main:brown[800],
      },
     secondary:{
      main:amber["A700"],
     },
     info:{
      main:blue[300]
     }
    },
  });
    return(
      <div>
        <Head>
        <title>adopción {title ? `${title}`:""} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <ThemeProvider theme={theme}>
      <div className={style.conatiner}>
      {children}
      </div>
      </ThemeProvider>
    </div>
    )
}